### PR TITLE
Add GitHub Action dart-package-analyzer.yml

### PR DESCRIPTION
**Pull request by cclauss**
@chimon2000 Your review, please?

Output: https://github.com/TheAlgorithms/Dart/runs/1253813888

Related to #86, #87, and #88

# Welcome to Dart community

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
@axel-op Your review please.

**Comment by axel-op** [comment]
> @axel-op Your review please.

This repo is actually not a package (it does not respect the [package layout conventions](https://dart.dev/tools/pub/package-layout)), that's why these checks are failing (there is no `pubspec.yaml`...)

**Comment by cclauss** [comment]
Thanks @axel-op 

I am not a Dart guy...  What is the best way to create a GitHub Action that behaves like
https://github.com/TheAlgorithms/Dart/blob/master/.travis.yml

**Comment by axel-op** [comment]
@cclauss Try something like this:

```yml
name: Analyze

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    container: google/dart:2
    
    steps:
      - uses: actions/checkout@v2
      - name: Analyze
        run: dart analyze
      - name: Format
        run: |
          OUTPUT=$(dart format . -o none)
          if [ ! -z "$OUTPUT" ]; then exit 1; fi
```

**Review by shellhub — APPROVED** [review]
LGTM

**Comment by axel-op** [comment]
@cclauss You're welcome!

**Comment by cclauss** [comment]
@axel-op I changed
```
OUTPUT=$(dart format . -o none)
if [ ! -z "$OUTPUT" ]; then exit 1; fi
# -->
dart format --set-exit-if-changed .
```
Merci beaucoup!

**Pull request merged**
