### PR TITLE
Implementation of singly linked list in Dart

### PR DESCRIPTION
**Pull request by nandikajain**
# Welcome to Dart community

### **Describe your change:**

* [x] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Dart files are placed inside an existing directory.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Parowicz** [comment]
Hello! Looks like we already have [Linked List](https://github.com/TheAlgorithms/Dart/blob/master/data_structures/linked_list.dart) implementation. Could you point differences between already existing one and your proposal?

You could also reuse test cases from existing implementation.

**Comment by nandikajain** [comment]
Oh!
Since it was not in the Linked List folder, I did not notice. The linked List folder only had one code for circular linked list.
I guess it should be moved in the linked list folder then!

**Comment by nandikajain** [comment]
Will this PR be considered under Hacktoberfest?

**Comment by Parowicz** [comment]
Well, only if merged.

**Comment by nandikajain** [comment]
Okay, I will add the implementation of Doubly Linked List, will it be considered?

**Comment by Parowicz** [comment]
Yea, we don't have any implementation of doubly linked list yet.
List of implemented algorithms can be found in [DIRECTORY.md](https://github.com/TheAlgorithms/Dart/blob/master/DIRECTORY.md)

**Pull request closed without merging**
