### PR TITLE
Linked list tests

### PR DESCRIPTION
**Pull request by Parowicz**
# Welcome to Dart community

Hello I've added test cases for old linked list implementation. Test ware written in https://pub.dev/packages/test 
Will they work with new CI?

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [x] Documentation change?

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by cclauss** [comment]
Awesome!  Please uncomment line 9 of `.github/workflows/dart_test_analyze_format.yml`

**Comment by cclauss** [comment]
Cool!  Please add a `tests/` directory.

**Comment by cclauss** [comment]
I sense that the tests go into `/tests/` and then they are automatically run but if they are elsewhere then the full path must be specified in the `dart test` command.

Thanks for getting us to our first running test.  Now we should require that all future PRs have tests.

**Comment by Parowicz** [comment]
That's my bad. I'll make another pull request where all tests from file are going to run.
I got distracted by errors. I will fix small ones.

**Pull request merged**
