### PR TITLE
first set bit

### PR DESCRIPTION
**Pull request by Ganesh-Agarwal-25**
The task is to print the position of first set bit found from right side in the binary representation of the number.
This PR is for Hacktober fest 2020.

# Welcome to Dart community

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by Ganesh-Agarwal-25** [comment]
@Parowicz , please review and merge for Hacktober 2020.

**Comment by Ganesh-Agarwal-25** [comment]
@Parowicz  please review and merge for hacktober.

**Comment by Parowicz** [comment]
What about tests?

**Comment by akashgk** [comment]
@Ganesh-Agarwal-25  can you add the tests for these?

**Pull request closed without merging**
