### PR TITLE
Create peak_element.dart

### PR DESCRIPTION
**Pull request by neha-hasija17**
This is a program to find the index of the peak element in a given array using binary search approach.
A peak element is an element which is greater than both of its neighbors.
This Pull Request is for HacktoberFest 2020

# Welcome to Dart community

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by neha-hasija17** [comment]
@Parowicz please review this program.

**Comment by neha-hasija17** [comment]
@Parowicz please help me in adding tests, as I am a beginner, and Dartpad doesn't support test library.

**Comment by neha-hasija17** [comment]
@Parowicz this pull request is for hacktoberfest 2020

**Comment by neha-hasija17** [comment]
Thankyou sir. please merge this as well :)

**Comment by Parowicz** [comment]
Looks perfect! Thank You!

**Comment by neha-hasija17** [comment]
Thankyou sir.

**Comment by neha-hasija17** [comment]
@Parowicz  please remove the label of tests are needed from this PR. :)

**Pull request merged**
