### PR TITLE
Create timSort.dart

### PR DESCRIPTION
**Pull request by ShivamGoyal1899**

### CODE REVIEW

**Comment by stepfencurryxiao** [comment]
Thanks

**Comment by ShivamGoyal1899** [comment]
@stepfencurryxiao Can you please add me to the contributors' list of **TheAlgorithms**?

**Comment by stepfencurryxiao** [comment]
Hi @ShivamGoyal1899! Do you mean to create a contributor.md file in this repo and add you to it?

**Comment by ShivamGoyal1899** [comment]
@stepfencurryxiao Actually, I was talking about adding me to maintainers of the organization, if you guys do that. I would love to contribute and maintain Dart & R Repositories.

About the contributor.md surely we can make it. If you want one to be created, I will be happy to add it.

**Comment by stepfencurryxiao** [comment]
I'm just a member of this organization, but you can email @AnupKumarPanwar and he may invite you.

**Pull request merged**
