### PR TITLE
Create magic_number.dart

### PR DESCRIPTION
**Pull request by neha-hasija17**
This Pull request is for HacktoberFest 2020

# Welcome to Dart community

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

### **Checklist:**
* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Dart files are placed inside an existing directory.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Review by Parowicz — CHANGES_REQUESTED** [review]
Hello, could you describe what example algorithm it is? Maybe some hyperlink or in-code comments?

**Comment by neha-hasija17** [comment]
> Hello, could you describe what example algorithm it is? Maybe some hyperlink or in-code comments?

you may refer this link for further details about magic number. Usually it is calculated with a recursive approach but I was inspired by the efficient method given in this link.

https://www.geeksforgeeks.org/check-number-magic-recursive-sum-digits-1/

**Comment by neha-hasija17** [comment]
@Parowicz you may as well check (#113). thankyou for the review

**Review by Parowicz — APPROVED** [review]
Thank you. Really interesting algorithm!

**Comment by neha-hasija17** [comment]
thankyou so much.

**Comment by neha-hasija17** [comment]
kindly review #113 as well :)

**Pull request merged**
