### PR TITLE
Null safety migration

### PR DESCRIPTION
**Pull request by domesticmouse**
# Welcome to Dart community

### **Describe your change:**

Null safety migration

### **Checklist:**
* [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [x] This pull request is all my own work -- I have not plagiarized.
* [x] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [x] All new Dart files are placed inside an existing directory.
* [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

**Comment by akashgk** [comment]
thanks @domesticmouse. thanks for this super big task. we will review it. i was planning on listing all the files with no tests and adding tests to the old files. so we can be sure about that algorithms are working as expected

**Comment by domesticmouse** [comment]
> thanks @domesticmouse. thanks for this super big task... i was planning on listing all the files with no tests and adding tests to the old files. so we can be sure about that algorithms are working as expected when we migrate to null safety 

Please feel free to adopt this PR as the basis of your work. Most of the change in this PR is the result of tooling, `dart fix` and `dart migrate`. 

The current tests pass.

**Review by fahami — CHANGES_REQUESTED** [review]
I suggest to change lints version to 1.0.1 to make it compatible to Dart 2.12

**Comment by domesticmouse** [comment]
> Thank you @domesticmouse , I was checking in and I suggest to change lints version to 1.0.1 to make it compatible to Dart 2.12

I've up-revved the minimum version to match `lints` minimum Dart version. I don't see the upside of supporting all the way back to Dart 2.12, as the current stable is Dart 2.18.3 and Dart 2.19.0 is already in beta release.

**Pull request closed without merging**
